"""Parametric OpenInteriorCAD window object."""

import math

import FreeCAD as App
import Part
from pivy import coin


WINDOW_TYPE = "OpenInteriorCAD::Window"


def rebuild_host_wall(window):
    """Rebuild host wall after window parameter changes."""

    wall = getattr(
        window,
        "HostWall",
        None,
    )

    if wall is None:
        return

    try:
        from OICWall import rebuild_from_wall

        rebuild_from_wall(
            wall
        )

    except Exception as error:
        App.Console.PrintError(
            "OpenInteriorCAD: nie udało się "
            "przebudować ściany po zmianie okna: "
            f"{error}\n"
        )


class WindowProxy:
    """Parametric window attached to a wall."""

    TYPE_ID = WINDOW_TYPE

    def __init__(
        self,
        obj,
        wall=None,
        width=1200.0,
        height=1500.0,
        sill_height=900.0,
        offset=800.0,
    ):
        self._add_properties(
            obj
        )

        obj.Proxy = self

        if wall is not None:
            obj.HostWall = wall

        obj.Width = width
        obj.Height = height
        obj.SillHeight = sill_height
        obj.Offset = offset

        self.rebuild_geometry(
            obj
        )

    def _add_properties(
        self,
        obj,
    ):
        """Create window properties."""

        if "OICType" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyString",
                "OICType",
                "OpenInteriorCAD",
                "Semantic object type.",
            )

        if "HostWall" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyLink",
                "HostWall",
                "Okno",
                "Ściana, w której znajduje się okno.",
            )

        if "Width" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyLength",
                "Width",
                "Okno",
                "Szerokość otworu okiennego.",
            )

        if "Height" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyLength",
                "Height",
                "Okno",
                "Wysokość otworu okiennego.",
            )

        if "SillHeight" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyLength",
                "SillHeight",
                "Okno",
                "Wysokość parapetu od poziomu podłogi.",
            )

        if "Offset" not in obj.PropertiesList:
            obj.addProperty(
                "App::PropertyLength",
                "Offset",
                "Okno",
                "Odległość od początku ściany.",
            )

        obj.OICType = self.TYPE_ID

    def _validate_parameters(
        self,
        obj,
    ):
        """Keep window inside its host wall."""

        wall = obj.HostWall

        if wall is None:
            return

        wall_length = wall.Length.Value
        wall_height = wall.Height.Value

        if obj.Width.Value >= wall_length:
            obj.Width = max(
                1.0,
                wall_length - 1.0,
            )

        if obj.Offset.Value < 0.0:
            obj.Offset = 0.0

        maximum_offset = max(
            0.0,
            wall_length - obj.Width.Value,
        )

        if obj.Offset.Value > maximum_offset:
            obj.Offset = maximum_offset

        if obj.SillHeight.Value < 0.0:
            obj.SillHeight = 0.0

        if obj.SillHeight.Value >= wall_height:
            obj.SillHeight = max(
                0.0,
                wall_height - 1.0,
            )

        maximum_height = max(
            1.0,
            wall_height - obj.SillHeight.Value,
        )

        if obj.Height.Value > maximum_height:
            obj.Height = maximum_height

    def rebuild_geometry(
        self,
        obj,
    ):
        """
        Update window placement.

        Actual opening is generated by OICWall.
        Symbol is drawn by WindowViewProvider.
        """

        wall = obj.HostWall

        if wall is None:
            obj.Shape = Part.Shape()
            return

        self._validate_parameters(
            obj
        )

        heading = wall.Heading.Value

        angle_rad = math.radians(
            heading
        )

        ux = math.cos(
            angle_rad
        )

        uy = math.sin(
            angle_rad
        )

        wall_start = wall.StartPoint

        window_position = App.Vector(
            wall_start.x
            + ux * obj.Offset.Value,
            wall_start.y
            + uy * obj.Offset.Value,
            wall_start.z,
        )

        # Symbol okna jest rysowany w lokalnym
        # układzie współrzędnych obiektu.
        obj.Placement = App.Placement(
            window_position,
            App.Rotation(
                App.Vector(
                    0.0,
                    0.0,
                    1.0,
                ),
                heading,
            ),
        )

        obj.Shape = Part.Shape()

    def execute(
        self,
        obj,
    ):
        """FreeCAD recompute callback."""

        self.rebuild_geometry(
            obj
        )

    def onChanged(
        self,
        obj,
        property_name,
    ):
        """React to editable window properties."""

        if property_name not in {
            "HostWall",
            "Width",
            "Height",
            "SillHeight",
            "Offset",
        }:
            return

        required = {
            "HostWall",
            "Width",
            "Height",
            "SillHeight",
            "Offset",
        }

        if not required.issubset(
            set(
                obj.PropertiesList
            )
        ):
            return

        try:
            self.rebuild_geometry(
                obj
            )

            rebuild_host_wall(
                obj
            )

        except Exception as error:
            App.Console.PrintError(
                "OpenInteriorCAD window update error: "
                f"{error}\n"
            )

    def onDocumentRestored(
        self,
        obj,
    ):
        """Restore window after opening document."""

        self._add_properties(
            obj
        )

        obj.Proxy = self


class WindowViewProvider:
    """2D architectural window symbol."""

    def __init__(
        self,
        view_object,
    ):
        self.root = None

        view_object.Proxy = self

    def attach(
        self,
        view_object,
    ):
        """Create window symbol scene."""

        try:
            self.root = coin.SoSeparator()

            view_object.addDisplayMode(
                self.root,
                "WindowSymbol",
            )

            self._rebuild_symbol(
                view_object.Object
            )

        except Exception as error:
            App.Console.PrintError(
                "OpenInteriorCAD window symbol error: "
                f"{error}\n"
            )

    def _add_line(
        self,
        parent,
        point1,
        point2,
    ):
        """Add one local Coin3D line."""

        separator = coin.SoSeparator()

        coords = coin.SoCoordinate3()

        coords.point.setValues(
            0,
            2,
            [
                (
                    point1.x,
                    point1.y,
                    point1.z,
                ),
                (
                    point2.x,
                    point2.y,
                    point2.z,
                ),
            ],
        )

        line = coin.SoLineSet()

        line.numVertices.setValue(
            2
        )

        separator.addChild(
            coords
        )

        separator.addChild(
            line
        )

        parent.addChild(
            separator
        )

    def _rebuild_symbol(
        self,
        window,
    ):
        """Build window symbol in local coordinates."""

        if self.root is None:
            return

        self.root.removeAllChildren()

        wall = window.HostWall

        if wall is None:
            return

        width = window.Width.Value

        if width <= 0.001:
            return

        thickness = wall.Thickness.Value

        # Jasny symbol — czytelny na ciemnym tle.
        color = coin.SoBaseColor()

        color.rgb = (
            0.90,
            0.95,
            1.00,
        )

        style = coin.SoDrawStyle()

        style.lineWidth = 2.0

        self.root.addChild(
            color
        )

        self.root.addChild(
            style
        )

        z = 150.0

        # Dwie linie po obu stronach osi ściany.
        frame_offset = min(
            thickness * 0.22,
            30.0,
        )

        p1 = App.Vector(
            0.0,
            -frame_offset,
            z,
        )

        p2 = App.Vector(
            width,
            -frame_offset,
            z,
        )

        p3 = App.Vector(
            0.0,
            frame_offset,
            z,
        )

        p4 = App.Vector(
            width,
            frame_offset,
            z,
        )

        self._add_line(
            self.root,
            p1,
            p2,
        )

        self._add_line(
            self.root,
            p3,
            p4,
        )

        # Krótkie zamknięcia na końcach ramy.
        self._add_line(
            self.root,
            p1,
            p3,
        )

        self._add_line(
            self.root,
            p2,
            p4,
        )

    def updateData(
        self,
        obj,
        property_name,
    ):
        """Rebuild symbol when window changes."""

        if property_name in {
            "HostWall",
            "Width",
            "Offset",
        }:
            self._rebuild_symbol(
                obj
            )

    def getDisplayModes(
        self,
        view_object,
    ):
        return [
            "WindowSymbol",
        ]

    def getDefaultDisplayMode(
        self,
    ):
        return "WindowSymbol"

    def setDisplayMode(
        self,
        mode,
    ):
        return mode

    def onChanged(
        self,
        view_object,
        property_name,
    ):
        return

    def dumps(
        self,
    ):
        return None

    def loads(
        self,
        state,
    ):
        return None


def create_window(
    document,
    wall,
    width=1200.0,
    height=1500.0,
    sill_height=900.0,
    offset=800.0,
    name="Window",
):
    """Create a parametric OpenInteriorCAD window."""

    obj = document.addObject(
        "Part::FeaturePython",
        name,
    )

    obj.Label = "Window"

    WindowProxy(
        obj,
        wall=wall,
        width=width,
        height=height,
        sill_height=sill_height,
        offset=offset,
    )

    WindowViewProvider(
        obj.ViewObject
    )

    document.recompute()

    try:
        obj.ViewObject.DisplayMode = (
            "WindowSymbol"
        )

    except Exception:
        pass

    obj.ViewObject.Visibility = True

    rebuild_host_wall(
        obj
    )

    document.recompute()

    return obj